-- Auto-generated by scripts/generate_seed.py. Do not edit units by hand;
-- edit the generator and re-run it instead.

CREATE TABLE IF NOT EXISTS units (
    id              TEXT PRIMARY KEY,
    token           TEXT NOT NULL,
    geofence_radius_km DOUBLE PRECISION NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS telemetry_events (
    id          BIGSERIAL PRIMARY KEY,
    unit_id     TEXT NOT NULL REFERENCES units(id),
    lat         DOUBLE PRECISION NOT NULL,
    lon         DOUBLE PRECISION NOT NULL,
    battery_pct DOUBLE PRECISION NOT NULL,
    signal_pct  DOUBLE PRECISION NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_telemetry_unit_time ON telemetry_events (unit_id, received_at DESC);

CREATE TABLE IF NOT EXISTS alerts (
    id          BIGSERIAL PRIMARY KEY,
    unit_id     TEXT NOT NULL REFERENCES units(id),
    alert_type  TEXT NOT NULL CHECK (alert_type IN ('low_battery', 'signal_lost', 'geofence_breach')),
    details     TEXT NOT NULL,
    fired_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_alerts_unit_time ON alerts (unit_id, fired_at DESC);

INSERT INTO units (id, token, geofence_radius_km) VALUES
    ('unit-001', '1a04ec57d4aa086729dceedc25f50d49', 15.0),
    ('unit-002', 'c0ecaa0712222c6ae2e37322d5dcb3b1', 10.0),
    ('unit-003', '5f50f78867dec39e3bc5aec6639a716f', 6.0),
    ('unit-004', 'c7fb9b75df8c5aa6d41f2b111e832fe1', 15.0),
    ('unit-005', 'a1774420407f0cf4edc7b9797edf7368', 15.0),
    ('unit-006', '9196e8a9fdee73db54a9a4b78ec47e36', 4.0),
    ('unit-007', 'e4b249a106ae7e4f0145c98c66adabd3', 6.0),
    ('unit-008', '5c048b509a8fd54e4e19f1eb43bc118a', 8.0),
    ('unit-009', 'af5f43abb6833f2e518c9ba944137ff9', 6.0),
    ('unit-010', 'f74048cc908d0bf74ddb24c007519c78', 5.0),
    ('unit-011', '9eb6fcdeffb52aac0511a843d44dfbaa', 8.0),
    ('unit-012', 'b7cbb0904bca7818c8480ab188614cda', 5.0),
    ('unit-013', '9fe8f21b11d1895b83e35bbda2431eae', 6.0),
    ('unit-014', '9bf56294cc7a5e1ce8cd61a8025da96b', 3.0),
    ('unit-015', 'f0312b77c5482ad4c8fdda326ff2cc02', 8.0),
    ('unit-016', '3a73c56b13264b95cf9b71ba0a6e1183', 8.0),
    ('unit-017', '7732528f24ed792545fd17d970901c47', 3.0),
    ('unit-018', 'da0cda4f29fb4a00db8142599bf8f8a5', 10.0),
    ('unit-019', '44089a2cdc450a50c76268f8d611ac40', 6.0),
    ('unit-020', '620c58fa4167666ae453f484e531d347', 8.0),
    ('unit-021', '0643a08dd33aab46bbed7db2856c28c2', 8.0),
    ('unit-022', 'dae8da3c1eb59f7e9dd687aea74c2ca0', 5.0),
    ('unit-023', '201b2525f58a32c13c018618c31543bb', 2.0),
    ('unit-024', '435e4b2ff9093f0888472c1b994c0861', 6.0),
    ('unit-025', 'd7cb092f01611e2b0b6fea00a110b10c', 15.0),
    ('unit-026', 'b78ddc7f6be3ca8a2d110f382a357cbd', 3.0),
    ('unit-027', '25df0b5b58706f685db2d40ef3789778', 8.0),
    ('unit-028', '76e321f54928a5b570dd6c17d674b50c', 5.0),
    ('unit-029', '4f0bb23d9d35c95973efc4dfc8ee9dff', 4.0),
    ('unit-030', 'f06389f7acffc62d62e2d28cd017a022', 6.0)
ON CONFLICT (id) DO NOTHING;
