#!/usr/bin/env python3
"""Generate the SwarmOps fleet seed data: unit IDs + auth tokens + geofence config.

This is dev/demo seed data, not a production secret store — in a real deployment
the unit registry (and tokens) would live in a proper secrets manager / Vault and
be provisioned per-device, not committed to git. For this project it's generated
once, deterministically, and checked in so `docker compose up` and the simulator
agree on the same fleet without any manual copy-pasting of tokens.

Regenerate with:  python scripts/generate_seed.py
Writes:
  seed/units.json   - source of truth, read by the simulator
  db/init.sql       - Postgres schema + INSERT statements generated from the JSON
"""
import json
import random
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UNIT_COUNT = 30
SEED = 1337  # deterministic fleet layout across regenerations

# Base = Rishon LeZion, Israel. All geofences are measured from this single base.
BASE_LAT = 31.9730
BASE_LON = 34.7925


def build_units():
    rng = random.Random(SEED)
    units = []
    for i in range(1, UNIT_COUNT + 1):
        unit_id = f"unit-{i:03d}"
        token = secrets.token_hex(16)
        # Most units patrol within 2-8km of base; a few long-range ones out to 15km.
        radius_km = round(rng.choice([2, 3, 4, 5, 5, 6, 8, 8, 10, 15]) * 1.0, 1)
        units.append({"id": unit_id, "token": token, "geofence_radius_km": radius_km})
    return units


def write_json(units):
    seed_dir = ROOT / "seed"
    seed_dir.mkdir(exist_ok=True)
    payload = {"base_lat": BASE_LAT, "base_lon": BASE_LON, "units": units}
    (seed_dir / "units.json").write_text(json.dumps(payload, indent=2) + "\n")


def write_sql(units):
    lines = [
        "-- Auto-generated by scripts/generate_seed.py. Do not edit units by hand;",
        "-- edit the generator and re-run it instead.",
        "",
        "CREATE TABLE IF NOT EXISTS units (",
        "    id              TEXT PRIMARY KEY,",
        "    token           TEXT NOT NULL,",
        "    geofence_radius_km DOUBLE PRECISION NOT NULL,",
        "    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS telemetry_events (",
        "    id          BIGSERIAL PRIMARY KEY,",
        "    unit_id     TEXT NOT NULL REFERENCES units(id),",
        "    lat         DOUBLE PRECISION NOT NULL,",
        "    lon         DOUBLE PRECISION NOT NULL,",
        "    battery_pct DOUBLE PRECISION NOT NULL,",
        "    signal_pct  DOUBLE PRECISION NOT NULL,",
        "    received_at TIMESTAMPTZ NOT NULL DEFAULT now()",
        ");",
        "CREATE INDEX IF NOT EXISTS idx_telemetry_unit_time ON telemetry_events (unit_id, received_at DESC);",
        "",
        "CREATE TABLE IF NOT EXISTS alerts (",
        "    id          BIGSERIAL PRIMARY KEY,",
        "    unit_id     TEXT NOT NULL REFERENCES units(id),",
        "    alert_type  TEXT NOT NULL CHECK (alert_type IN ('low_battery', 'signal_lost', 'geofence_breach')),",
        "    details     TEXT NOT NULL,",
        "    fired_at    TIMESTAMPTZ NOT NULL DEFAULT now()",
        ");",
        "CREATE INDEX IF NOT EXISTS idx_alerts_unit_time ON alerts (unit_id, fired_at DESC);",
        "",
        "INSERT INTO units (id, token, geofence_radius_km) VALUES",
    ]
    values = [
        f"    ('{u['id']}', '{u['token']}', {u['geofence_radius_km']})" for u in units
    ]
    lines.append(",\n".join(values) + "\nON CONFLICT (id) DO NOTHING;")
    (ROOT / "db" / "init.sql").write_text("\n".join(lines) + "\n")


def main():
    units = build_units()
    write_json(units)
    write_sql(units)
    print(f"Generated {len(units)} units -> seed/units.json, db/init.sql")


if __name__ == "__main__":
    main()
